### ISSUE TITLE
Dry run evaluation fails with filtered source

### ISSUE THREAD

**Issue by rushmorem** [ipetkov/crane#118]
Running `nix flake check --no-build` on a flake that hasn't been built before (which is usually the case in CI) results in an error message like:-

```
error: path '/nix/store/wkg1fvrldw8kg05vjwqz4vc5g5r878sl-source' is not valid
```

when using `cleanCargoSource`. You can see a [full backtrace here](https://github.com/rushmorem/crane-debug/actions/runs/3110722070/jobs/5042197109).

**Comment by ipetkov** [comment]
This is really unfortunate but I don't think there is a way to make `nix flake check --no-build` work with a filtered source being passed into `crane` :disappointed:  (but if anyone does please let me know!)

The crux of the issue is that we inspect/analyze things like `Cargo.lock` at evaluation time so that we can build up a chain of derivations which will fetch sources from crates.io, and we cannot do this from inside of the sandbox. When the source input is a plain path nix can easily access the file at evaluation time. If the source input is another derivation, the file can still be access if `import-from-derivation` is enabled (which is the case for flakes).

Except it appears that running `nix flake check --no-build` prevents all derivations (including `filterSource`/`cleanSourceWith`) from being built, which means that the evaluation will fail when it tries to read those files. IMO nix should make an exception and evaluate `filterSource` derivations even with `--no-build` since "building" those derivations is just creating a subset of sources which may already be in the store, but you could argue that the current behavior is correct if you expect `--no-build` to not touch the store _at all_.

The only work around that I can think of is to not use a source filter and scope all relevant files to a subdirectory which can be passed in as an input. Even changing the input to use `pkgs.lib.cleanSource ./.` exhibits the same behavior (meaning `filterSource` is the culprit here and not specifically `craneLib.cleanCargoSource`)

**Comment by rushmorem** [comment]
That's totally understandable. Thanks for the explanation. Since this is neither something that can be fixed nor specific to Crane, I'm going to close it. Feel free to re-open if you want it to remain open.
