### ISSUE TITLE
build script asks git for version

### ISSUE THREAD

**Issue by michaelglass** [ipetkov/crane#160]
Howdy

The build script that my crate uses calls `git describe` to write a version number into the output directory. When running under nix, the `.git` directory isn't copied over to the build directory even if I explicitly set it in  `buildPackage`'s `filter` param.

```
    let
        pkgs = import nixpkgs {
          inherit system;
        };

        craneLib = crane.lib.${system};

        gitFilter = path: (builtins.match ".*/.git/.*$" path) != null;
        gitOrCargo = path: type:
          (gitFilter path) || (craneLib.filterCargoSources path type);

        buildInputs = if pkgs.stdenv.isDarwin then [ pkgs.libiconv pkgs.darwin.apple_sdk.frameworks.Security ] else [ ];
        nativeBuildInputs = [ pkgs.git ];

        my-crate = craneLib.buildPackage
          {
            src = nixpkgs.lib.cleanSourceWith {
              src = ./.;
              filter = gitOrCargo;
            };
```

Any ideas? P.s. your library is wonderful thank you!

**Comment by ipetkov** [comment]
Thanks for the report @michaelglass ! Your filter invocation looks correct to me, though I think what is happening is that flakes will clean paths by default (i.e. the `./.` portion in your example) to omit stuff like version control files (you wouldn't want a new commit to invalidate all builds because git's internal data files changed)

I believe it may be possible to get the current flake's revision by using `self.rev` (or `self.shortRev`), perhaps you might need to use that as an alternative instead of checking the version number from git?

**Comment by michaelglass** [comment]
thanks! Will try to change the build script to use env vars instead of `git` directly. 

other relevant threads: 
- https://discourse.nixos.org/t/git-describe-like-attributes-for-flakes/10805
- https://github.com/NixOS/nix/issues/7201
