### ISSUE TITLE
Generate a `rust-project.json` file for rust-analyzer

### ISSUE THREAD

**Issue by fasterthanlime** [ipetkov/crane#169]
So one of the points of using nix to build my (real-world) rust projects is that I can declare all my native dependencies in nix and they'll build on any underlying Linux distribution. For that to really work, I need to use nix for `check` / `clippy` / running tests as well.

rust-analyzer is able to work with projects that aren't built directly with cargo: you can specify a custom check command, for example. But it needs to be able to find the sources and the compiled proc macros.

The way this works is through a `rust-project.json` file: https://rust-analyzer.github.io/manual.html#non-cargo-based-projects

The situation is a bit awkward with crane, since it _does_ use cargo, just in a different environment, so maybe `rust-project.json` is not the best approach and one ought to use a nix-shell environment instead? Still, it's probably worth a try.

**Comment by ipetkov** [comment]
I suppose there might be a way to configure the `clippy`/`check` derivations to save an output file of their findings and somehow convince rust-analyzer to use it instead of trying to run cargo directly. The one downside to that is the derivation _must_ succeed for it to materialize in the store (so if a denied clippy lint fires and fails the build we won't be able to capture the results [unless we want to consider it a success anyway from Nix's perspective]).

Usually I stick to using a dev-shell (something like `pkgs.mkShell { inputsFrom = myCrate }`) which can provide all the necessary project dependencies on the path which should make rust-analyzer happy as it is closer to a non-sandboxed way of building things.

That said if there is a way to support it that isn't too annoying to set up I'd be happy to explore it!

**Comment by fasterthanlime** [comment]
> Usually I stick to using a dev-shell (something like `pkgs.mkShell { inputsFrom = myCrate }`) which can provide all the necessary project dependencies on the path which should make rust-analyzer happy as it is closer to a non-sandboxed way of building things.

Mhh, I'm interested in that, but no luck:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/7998310/202597515-e3420519-189a-4919-8d12-a79946a2c38c.png">

(with [this flake](https://gist.github.com/fasterthanlime/08b9fb85ea414fc564779ea8002df310))

**Comment by ipetkov** [comment]
Whoops my example was wrong, `inputsFrom` takes a list, not a value, so that should be `inputsFrom = [ futile ];`

**Comment by dpc** [comment]
You want to use `nix develop` for sure. I can offer our [flake.nix](https://github.com/fedimint/fedimint/blob/master/flake.nix) and [dev-env setup document](https://github.com/fedimint/fedimint/blob/master/docs/dev-env.md) as inspiration. Not saying everything there is top perfect, but it's been working very well for large and diverse group of contributors.

**Comment by fasterthanlime** [comment]
So here's what I landed on:

  * Set up [direnv](https://direnv.net/), hook it to my shell (zsh)
  * Set up the `mkhl.direnv` VSCode extension (works over SSH remote)
  * Use [nix-direnv](https://github.com/nix-community/nix-direnv)
  * Convert my old `.env` to an `.envrc`, which looks something like:

```bash
if ! has nix_direnv_version || ! nix_direnv_version 2.2.0; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.2.0/direnvrc" "sha256-5EwyKnkJNQeXrRkYbwwRBcXbibosCJqyIUuz9Xq+LRc="
fi

nix_direnv_watch_file rust-toolchain.toml
use flake
```

My devShell looks something like:

```nix
        devShells.default = pkgs.mkShell {
          inputsFrom = [ bin ];
          packages = [ pkgs.just ];
        };
```

(probably should add more packages in there).

This all works as expected, rust-analyzer works fine, everything is great. Thanks for the advice everyone!
