### ISSUE TITLE
`zstd` seems to use default (1) number of threads

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#182]
We've noticed that on fast machines `zstd` usage in crane appears slow and bottlenecks on saturating only one CPU, even though `zstd` is supposed to support multi-threaded compression&decompression.

**Comment by ipetkov** [comment]
As far as I can tell, `zstd` does not support multi-threaded decompression: https://github.com/facebook/zstd/issues/2470

**Comment by dpc** [comment]
Well, we'll take what we can. AFAICT `zstd -o ...` used currently for compression could use `-T0` and we'll see if decompression is still an issue.

**Comment by ipetkov** [comment]
I was going to wonder whether zstd compression is deterministic and according to https://github.com/facebook/zstd/issues/2079 it is!

Though it looks like cargo artifacts themselves aren't deterministic. That said I have no issue with using `-T0` since we'd have to solve that non-determinism separately anyway

@dpc feel free to try out #183
