### ISSUE TITLE
Trouble building a project based on a version of `dioxus` using `include_str!("../../../examples/...")` across crates within a single git repo / cargo workspace?

### ISSUE THREAD

**Issue by mstone** [ipetkov/crane#184]
# Test case

Minimal reproducer here: https://github.com/mstone/crane-bug-dioxus.

If possible, please let me know if either

a. I'm doing something obviously mistaken in this example and, if so, what? or
b. this is in principle supposed to work but doesn't today, but there is nevertheless a workaround already provided by the `crane` API, and if so, what is it?

# Context

While trying to use `crane` to build a flake containing a Rust-based program targeting `wasm32-unknown-unknown` based on [dioxus](https://github.com/DioxusLabs/dioxus)' current git `HEAD`, I've started running into build errors where `crane`'s `...-deps` derivation fails to build in situations where `cargo build` & friends succeed, I think *maybe* because `crane`'s deps-processing code is dropping `examples`-related directories even though Dioxus' current implementation tries to `include_str!(...)` a file with the path `.../examples/rsx_usage.rs`?

Thanks!

-- Michael

**Comment by mstone** [comment]
@ipetkov -- Thanks for the suggestion; I've tried adding it to the test case I prepared here https://github.com/mstone/crane-bug-dioxus/commit/cbab895eac2b330e2e6f1a69b20020f92e9f160b but unfortunately `nix build` still fails in the same way!

Regarding `cleanCargoSource` -- that was part of what I was wondering about, except here the file being included does end in `.rs`, and it's the `..-deps` / `cargoBuildArtifacts` derivation that is failing to build.

(Also, since I am still learning my way around the `crane` source code: is `cleanCargoSource` much involved in defining the derivation used to build projects' dependencies?)

**Comment by ipetkov** [comment]
@mstone thanks for the detailed analysis! I'm unfortunately away from a computer so I can look more closely later. 

Could you try building the project (outside of Nix) using `cargo vendor` (and the instructions it prints out)?

Generally speaking, local paths and vendored dependencies tend not to mix well (but a lot of projects don't realize it because using deps from crates.io or from got repos *happens* to work due to implementation details). If the `cargo vendor` approach also fails then it's likely an issue that should be solved/massaged upstream

**Comment by mstone** [comment]
@ipetkov I'm glad you found the analysis helpful. Happily, also mere moments ago, @jkelleyrtp also kindly adjusted the Dioxus code via https://github.com/DioxusLabs/dioxus/commit/b254d9e761ecc51589113f2249879d9d6ef0f080 based on this investigation to change their approach on the grounds that `cargo publish` or similar ultimately does not support these kinds of cross-crate `include_str!()` references!

**Comment by mstone** [comment]
(Also, to confirm your hypothesis, I tried the `cargo vendor` method you suggested above and indeed, following the resulting instructions does reproduce the error in question. As a result: absent a way to detect the situation in order to give a more helpful warning / error message, maybe the best we can realistically do is to add a note to some documentation [ perhaps, an FAQ or a debugging / error-handling guide? ] to help direct readers who do run into similar problems to the current solution?)

**Comment by ipetkov** [comment]
@mstone glad to hear the issue was resolved upstream!

> As a result: absent a way to detect the situation in order to give a more helpful warning / error message, maybe the best we can realistically do is to add a note to some documentation [ perhaps, an FAQ or a debugging / error-handling guide? ] to help direct readers who do run into similar problems to the current solution?

Currently there is the FAQ section of the README.md, I think we could add something there for the next person who runs into this. Since you just ran into it, would you be interested in writing up a short summary on it? Doesn't have to be perfect and I'm happy to help too :)
