### ISSUE TITLE
Stripping and patching interpreter paths are done after compressing deps

### ISSUE THREAD

**Issue by Panke** [ipetkov/crane#202]
While looking into #194 in a nix shell I spotted this:

```text
nstalling
compressing target to /nix/store/6755i89g27klxblbr5idvjpsqbh342z4-cargo-package-deps-0.0.1/target.tar.zst
/*stdin*\            : 20.59%   (   168 MiB =>   34.5 MiB, /nix/store/6755i89g27klxblbr5idvjpsqbh342z4-cargo-package-deps-0.0.1/target.tar.zst) 
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/6755i89g27klxblbr5idvjpsqbh342z4-cargo-package-deps-0.0.1
strip is /nix/store/dq0xwmsk1g0i2ayg6pb7y87na2knzylh-gcc-wrapper-11.3.0/bin/strip
patching script interpreter paths in /nix/store/6755i89g27klxblbr5idvjpsqbh342z4-cargo-package-deps-0.0.1
checking for references to /build/ in /nix/store/6755i89g27klxblbr5idvjpsqbh342z4-cargo-package-deps-0.0.1...
``` 

Maybe it doesn't matter, but it does strike me as odd that compression is not the very last step.

**Comment by ipetkov** [comment]
Thanks for the report @Panke ! Normally you'd want the final binaries themselves to be stripped of debug symbols and their interpreter paths patched. I don't think it matters too much for the cargo artifacts since if the build actually produces binaries in another stage they will get patched and stripped then. Hence we compress the artifacts and write them to the output in a single operation rather than copy first, and compress (and delete the originals) in multiple steps.

As long as it's not causing problems it should be safe to ignore

**Comment by ipetkov** [comment]
Going to close this as I don't think there is anything that needs fixing atm, but feel free to reopen if there is!
