### ISSUE TITLE
Only 4 architectures supported?

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#243]
When I try to use `nix flake show` on my project it fails on:

```
craneLib = crane.lib.${system}.overrideToolchain fenixToolchain
```

complaining that `i686-linux` doesn't exist. Which is weird as when I look at `crane`'s `flake.nix` it seems to use `flake-utils.lib.eachDefaultSystem` just like my flake.

But when I do `nix flake show 'github:ipetkov/crane?ref=v0.11.2'` indeed I see only 4 archs:

```
├───devShells
│   ├───aarch64-darwin
│   │   └───default: development environment 'nix-shell'
│   ├───aarch64-linux
│   │   └───default: development environment 'nix-shell'
│   ├───x86_64-darwin
│   │   └───default: development environment 'nix-shell'
│   └───x86_64-linux
│       └───default: development environment 'nix-shell'
```

**Comment by ipetkov** [comment]
Yes you are correct that `flake-utils` [recently removed i686 from the default list of systems](https://github.com/numtide/flake-utils/pull/82)

I will note that the default systems are more of a convenience for anyone who wants to use `crane.lib.${system}` directly, but just because a default system isn't listed doesn't mean it is unsupported, it just requires manually instantiating nixpkgs.

I don't think there is much for us to change here, so I'm going to close, but feel free to reopen if there is something else to add!
