### ISSUE TITLE
Consider adding an API to vendor crates from multiple Cargo.lock files at once

### ISSUE THREAD

**Issue by Infinidoge** [ipetkov/crane#260]
Hello,
Crane is a fantastic addition to my Rust building workflow, however when trying to build a project with `-Zbuild-std`, I run into predictable name resolution errors, since Cargo lacks internet access.

Is there a currently supported way to properly build the `std` crate (or in this case, `core` and `alloc`) under Crane?

**Comment by ipetkov** [comment]
Hi @Infinidoge! My understanding is that `-Z build-std` requires that the toolchain include the `src` component to be present and installed.

One possible way to satisfy this is to [follow the custom-toolchain example](https://github.com/ipetkov/crane/blob/105e27adb70a9890986b6d543a67761cbc1964a2/examples/custom-toolchain/flake.nix) but specify `extensions = [ "rust-src" ];` (instead of `target = [ ... ];`).

Hope this helps!

**Comment by Infinidoge** [comment]
I actually already have that in my configuration.
(Before I added it, it gave me a message to `rustup component add rust-src`)

**Comment by Infinidoge** [comment]
Added `--offline` to my arguments, and apparently `std` depends on `cfg-if` (https://github.com/rust-lang/cfg-if), which it can't fetch due to the Nix sandbox.
There might be other crates it needs, but that is at least the first one it tries and fails to get.

One potential solution would be to emulate build-std in crane by manually packaging std for Nix, but I'd have to dig into how std is built to try and figure out how to do that

**Comment by ipetkov** [comment]
> One potential solution would be to emulate build-std in crane by manually packaging std for Nix
This might be difficult since every possible toolchain could have a different `Cargo.lock` file, especially as the stdlib depends on more crates over time...

Though it is worth noting that you can find the std-lib's `Cargo.lock` file at `~/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock` when using native rustup. I'm not sure where `oxalica/rust-overlay` will put the `rust-src` files but it could be possible to point `vendorDeps` to use it.

The hard part will be wiring up cargo's build of `std` to use it...

**Comment by Infinidoge** [comment]
`rust-overlay` seems to mirror the rustup location, `${toolchaih}/lib/rustlib/src/rust/Cargo.lock`
Hmm.

Is it possible to combine `cargoArtifacts`-compatible derivations together?

**Comment by Infinidoge** [comment]
Doing this works, apparently:
```nix
craneLib.buildPackage {
  src = craneLib.cleanCargoSource ./.;

  cargoExtraArgs = "-Zbuild-std=core";
  doCheck = false;

  cargoVendorDir = lib.crane.vendorCargoDeps {
    src = "${rustToolchain.passthru.availableComponents.rust-src}/lib/rustlib/src/rust";
  };
}
```

Combining vendored dirs together would work as a general case, then/

**Comment by Infinidoge** [comment]
For more context on this, I'm trying to write a simple operating system in Rust (targeting i386, which doesn't have a built-in target), and using Nix to build the entire thing.
I went ahead and pushed up what I currently have to [Infinidoge/i386-rust-os](https://github.com/Infinidoge/i386-rust-os) if you want to take a look.

[Here](https://github.com/Infinidoge/i386-rust-os/blob/master/kernel/default.nix) is the file where the above code is put into place. Right now it works fine because my kernel crate doesn't pull in any dependencies of its own, however when it does, I may need to merge the two somehow.

**Comment by ipetkov** [comment]
> Doing this works, apparently:

Oh that's great! Though in hindsight it shouldn't be that surprising since cargo will honor the vendor config's we are feeding it so it makes sense...

> Combining vendored dirs together would work as a general case, then.

Yeah, currently the APIs are designed around vendoring from a single `Cargo.lock` file, though it should be possible to massage things and allow vendoring from multiple `Cargo.lock` files! (perhaps it should be its own standalone API, but something to explore)

**Comment by Infinidoge** [comment]
I've been tinkering locally to try and get something working, and I've run into a strange issue:
```nix
vendorCargoDeps' = cargoLocks:
  let
    inherit (builtins)
      attrNames
      concatMap
      readFile
      fromToml;

    inherit (lib)
      concatMapStrings
      escapeShellArg;

    linkSources = sources: concatMapStrings
      (name: ''
        ln -s ${escapeShellArg sources.${name}} $out/${escapeShellArg name}
      '')
      (attrNames sources);

    locks = map fromTOML (map readFile cargoLocks);
    lockPackages = concatMap (lock: lock.package) locks;

    cargoConfigs = (lib.crane.findCargoFiles ./..).cargoConfigs; # TODO: Accept configs that aren't the local one

    vendoredRegistries = lib.crane.vendorCargoRegistries { inherit lockPackages cargoConfigs; };
    vendoredGit = lib.crane.vendorGitDeps { inherit lockPackages; };
  in
  pkgs.runCommandLocal "vendor-cargo-deps" { } ''
    mkdir -p $out
    cat >>$out/config.toml <<EOF
    ${vendoredRegistries.config}
    ${vendoredGit.config}
    EOF

    ${linkSources vendoredRegistries.sources}
    ${linkSources vendoredGit.sources}
  '';
```

Interestingly, this seems to just work, except for when it tries to run `vendorSingleRegistry`, where it errors out:
```
ln: failed to create symbolic link '/nix/store/f8wsap6jjx54iiqsp0cwycs8svihccnp-vendor-registry/bitflags-1.3.2/nsp78vb5r0kjbirlhf6f4famllgqrphh-cargo-package-bitflags-1.3.2': Permission denied
```

Any idea what might cause this?

**Comment by ipetkov** [comment]
I've opened https://github.com/ipetkov/crane/pull/287 which should address this! It adds `vendorMultipleCargoDeps` which allows specifying any number of `Cargo.lock` files (or their read/parsed equivalents)
