### ISSUE TITLE
`bindeps` feature breaks Lanzaboote build

### ISSUE THREAD

**Issue by Majiir** [ipetkov/crane#262]
I'm not familiar with `crane`, so apologies if this report is vague.

I have a system that uses [Lanzaboote](https://github.com/nix-community/lanzaboote), which depends on `crane`. After a `nix flake update`, the Lanzaboote tool fails to build. I narrowed down the trigger to this `crane` PR: https://github.com/ipetkov/crane/pull/258

Build log:

```
error: builder for '/nix/store/lnnlznwwm3z9yyjjhh0pxxx3bp1kg3y7-lanzaboote_stub-deps-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       >    Compiling sha2 v0.10.6
       >    Compiling uefi-services v0.16.0
       >    Compiling lanzaboote_stub v0.1.0 (/build/source)
       > error: linking with `rust-lld` failed: exit status: 1
       >   |
       >   = note: "rust-lld" "-flavor" "link" "/NOLOGO" "/entry:efi_main" "/subsystem:efi_application" "/build/rustcD0qWoA/symbols.o" "/build/source/target/x86_64-unknown-uefi/release/deps/crane_dummy-40d86f973d4ced01.crane_dummy.2d9b5714-cgu.0.rcgu.o" "/LIBPATH:/build/source/target/x86_64-unknown-uefi/release/deps" "/LIBPATH:/build/source/target/release/deps" "/LIBPATH:/nix/store/f7nb3i8za08prjnzrqzrzwa5x3nafrzh-rust-default-1.67.0-nightly-2022-11-21/lib/rustlib/x86_64-unknown-uefi/lib" "/nix/store/509wjj0vhpakxk87b0syv5jxiczpa62b-rust-std-1.67.0-nightly-2022-11-21-x86_64-unknown-uefi/lib/rustlib/x86_64-unknown-uefi/lib/libcompiler_builtins-bb944ea2862a44ff.rlib" "/NXCOMPAT" "/LIBPATH:/nix/store/f7nb3i8za08prjnzrqzrzwa5x3nafrzh-rust-default-1.67.0-nightly-2022-11-21/lib/rustlib/x86_64-unknown-uefi/lib" "/OUT:/build/source/target/x86_64-unknown-uefi/release/deps/crane_dummy-40d86f973d4ced01.efi" "/OPT:REF,ICF" "/DEBUG" "/NODEFAULTLIB"
       >   = note: rust-lld: error: <root>: undefined symbol: efi_main
       >           
       >
       > error: could not compile `lanzaboote_stub` due to previous error
       For full logs, run 'nix log /nix/store/lnnlznwwm3z9yyjjhh0pxxx3bp1kg3y7-lanzaboote_stub-deps-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/hgxlcbc75b0x29py2b99cmrahqr4rp6g-lanzaboote_stub-0.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/42kivkzyx201sc4mf92j6zc36ihmjfix-lzbt.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1dqhnlacyiii1vsi1rfzf16m7107lc6s-bootinstall.drv' failed to build
```

Other details:

- `x86_64-linux`
- `nixpkgs` @ a7cc81913bb3cd1ef05ed0ece048b773e1839e51 (with Bootspec patches applied on top)
- `lanzaboote` @ 3efb505a2a29de97accade8efee7a0505386a86d
- `rust-overlay` @ 802ff3314663ec7114f29a6e8b200dfc892023f8

**Comment by ipetkov** [comment]
Thanks for reporting this @Majiir, I apologize for the breakage!

Although #258 surfaced the issue, the real root cause is better noted by #268, specifically, autobin targets (e.g. having a `src/main.rs` or `src/bin/whatever.rs`) aren't well captured at this time. Before #258 `buildDepsOnly` was effectively only building the `lib` target, but after it `buildDepsOnly` is trying to build both the `lib` and `main.rs` targets. Since the `main.rs` target requires a `efi_main` symbol it fails to build since the [default `dummyrs`](https://github.com/ipetkov/crane/blob/77435dad14835fa2ac86490978e10618dc952593/lib/mkDummySrc.nix#L125-L138) file does not declare that symbol...

---
The solution to solving this is to provide your own custom `dummyrs` which introduces the necessary symbol! Currently it's a little awkward to write these dummy files since the same value is going to be used for build scripts (which are built for the build-host and not the provided target!), but I'm hoping once #268 is addressed the API will be a bit cleaner. But for now:

```nix
craneLib.buildPackage {
  # Other args go here

  dummyrs = pkgs.writeText "dummy.rs" ''
    #![allow(unused)]

    #![cfg_attr(
      any(target_os = "none", target_os = "uefi"),
      no_std,
      no_main,
    )]

    #[cfg_attr(any(target_os = "none", target_os = "uefi"), panic_handler)]
    fn panic(_info: &::core::panic::PanicInfo<'_>) -> ! {
        loop {}
    }

    #[cfg_attr(any(target_os = "none", target_os = "uefi"), export_name = "efi_main")]
    fn main() {}
  '';
}
```

**Comment by blitz** [comment]
@ipetkov Thanks for the workaround! I've added this to the lanzaboote repo for now.

Also thanks @Majiir for reporting this. :)

**Comment by Majiir** [comment]
Latest lanzaboote and crane are working for me. Thanks, all.
