### ISSUE TITLE
Dummy source derivation relying on source when using flake's self argument as source

### ISSUE THREAD

**Issue by winterqt** [ipetkov/crane#28]
When using `self` over `./.` for the source to `buildPackage`, the dummy source derivation relies on the source of the flake.

Good:
```json
    "inputSrcs": [
      "/nix/store/xxx-default-builder.sh",
      "/nix/store/xxx-Cargo.lock"
    ],
    "inputDrvs": {
      "/nix/store/xxx-dummy.rs.drv": [
        "out"
      ],
      "/nix/store/xxx-Cargo.toml.drv": [
        "out"
      ],
      "/nix/store/xxx-stdenv-darwin.drv": [
        "out"
      ],
      "/nix/store/xxx-bash-5.1-p16.drv": [
        "out"
      ]
    },
```

Bad:
```json
    "inputSrcs": [
      "/nix/store/xxx-default-builder.sh",
      "/nix/store/xxx-source"
    ],
    "inputDrvs": {
      "/nix/store/xxx-bash-5.1-p16.drv": [
        "out"
      ],
      "/nix/store/xxx-stdenv-linux.drv": [
        "out"
      ],
      "/nix/store/xxx-Cargo.toml.drv": [
        "out"
      ],
      "/nix/store/xxx-dummy.rs.drv": [
        "out"
      ]
    },
```

A reproduction is available at https://github.com/winterqt/crane-dummy-src-invalidation. This may be outside of Crane's control (as in, this may be an issue with how this attribute of flakes are implemented).

**Comment by ipetkov** [comment]
Hi @winterqt thanks for the reproduction flake! I was able to reproduce the issue and here are some of my observations:

Normally I stick my actual rust/cargo files in their own directory and then do `craneLib.buildPackage { src = ./mycrate; }` because I explicitly do not want changes to the flake (or other nix files) to needlessly invalidate any builds (namely the second build of the actual crate). Changing your flake to this pattern seems to resolve the issue (that is, changing the `main.rs` file only rebuilds the final derivation; without the change, changing the `main.rs` file leads to the dependencies being rebuilt as well).

---

The source dummification tries to only copy the exact files needed ([example](https://github.com/ipetkov/crane/blob/a233d51034ff871fcba8a74163076babc42cad5e/lib/mkDummySrc.nix#L97-L100)) in an attempt to make sure that the dummy-src derivation _only_ depends on things like `Cargo.{toml,lock}` files and not the rest of the flake source.

I don't know if there is some different kinds of interactions (i.e. source cleaning) that Nix does under the hood when a derivation's input is a sub-directory of the flake vs taking the entire flake source itself. Either way, this is undesired behavior and it would be good to find a way to avoid it (maybe an explicit `cleanSources` call is needed? will need to investigate it further)

**Comment by ipetkov** [comment]
Did a quick proof of concept of cleaning the source directory (to exclude anything we don't need for making the dummy source) and it appears to fix the cache invalidation bug. Will post a PR sometime later!

**Comment by ipetkov** [comment]
@winterqt I believe this is fixed now, please feel free to open an issue if you run into anything else!
