### ISSUE TITLE
`withCommonArgs` support

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#306]
Moved from https://github.com/ipetkov/crane/issues/300#issuecomment-1513473230 .

I was thinking a bit about it in the background, and maybe the whole `commonArgs` pattern should be used as an override / argument to `craneLib`.

So every `craneLib.mkDerivation args` would be under the hood a `craneLib.mkDerivation (mergeSmartly scope.commonArgs args)`. I'm not sure if `mergeSmartly` could be `builtins.mergeAttrs` or something a tiny bit more application-specific would be needed.

Normal users don't even have to know about it. It would be set to `{}` and job done. *However* if you at even https://crane.dev/examples/quick-start.html `commonArgs` is always used. Maybe... it should even just be the default way of doing thing? The examples would probably look prettier, and be easier to understand.

So the quick start example would be:

```
        craneLib = crane.lib.${system}.withCommonArgs {  // a little helper to avoid meh-scope-API
          src = craneLib.cleanCargoSource (craneLib.path ./.); // can I use `cranLib` here, or need decompose?

          buildInputs = [
            # Add additional build inputs here
          ] ++ lib.optionals pkgs.stdenv.isDarwin [
            # Additional darwin specific inputs can be set here
            pkgs.libiconv
          ];
        };

...

        my-crate = craneLib.buildPackage {
          inherit cargoArtifacts;
        };
```

Something like that. In my opinion this is much tidier than `(commonArgs //` all over the place.

Also `//` doesn't merge, so e.g. `buildInputs` need that ugly `buildInputs = commonArgs.buildInputs ++ [ new ones ];`

**Comment by ipetkov** [comment]
Thanks for the suggestion @dpc! I've given this some thought and although I can definitely see the usefulness of something like this, I'd be hesitant to actually implement/advertise it.

Yes passing `commonArgs` around is pretty noisy, but the upside is that anyone (both experienced and inexperienced with Nix) can easily tell at a glance where the data flows through. `withCommonArgs` as suggested would operate more closely to an overlay, which is still possible to debug if you know how/where to look but can become undebuggable otherwise. Given that there's enough that can go wrong in a complex configuration I don't want to make it harder on anyone to figure out what's going on :sweat_smile: 

All that said, this behavior is actually accessible (and [documented a bit differently](https://crane.dev/advanced/overriding-function-behavior.html)) today! Since everything basically delegates to `mkCargoDerivation`, all it takes is a little bit of manual wrangling, which I would say is not too difficult for anyone advanced enough to need this feature:

```nix
let
  craneLib = (inputs.crane.mkLib pkgs).overrideScope' (final: prev:
    let
      myCommonArgs = {
        src = final.cleanCargoSource (final.path ./.);

        buildInputs = lib.optionals pkgs.stdenv.isDarwin [
          pkgs.libiconv
        ];
      };
    in
    {
      # E.g. override args as intelligently as necessary here
      mkCargoDerivation = args: prev.mkCargoDerivation (lib.recursiveUpdate myCommonArgs args);
    });
in
{
  wholeWorkspace = craneLib.buildPackage {
    # defaults to src = ./.;
  };

  bar = craneLib.buildPackage {
    # But can still overwrite if needed
    src = craneLib.cleanCargoSource (craneLib.path ./bar);
  };
}
```

**Comment by dpc** [comment]
That's clever and works for me. Thanks.
