### ISSUE TITLE
Failing to build project that depends on libffi-sys

### ISSUE THREAD

**Issue by fracek** [ipetkov/crane#336]
I'm trying to use crane to build my project. My project indirectly depends on `libffi-sys` which builds libffi at build time. The build fails because the `configure` script cannot create the log file (permission denied). 

In general, I noticed getting a lot of "permission denied" while building deps, usually because they have a build script that places new files in the target directory (for example, the `v8` crate).

I made a repo reproducing this issue [here](https://github.com/fracek/crane-build-issue).

The full error is the following:

```
cargoArtifacts not set, will not reuse any cargo artifacts
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/abf7iq3lzk5h140kl2wkjgq3hm42wxv6-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
Executing configureCargoCommonVars
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
will append /build/source/.cargo-home/config.toml with contents of /nix/store/jidz82ydi3p4i6rkwn5sbzv7hfnrbw20-vendor-cargo-deps/config.toml
default configurePhase, nothing to do
@nix { "action": "setPhase", "phase": "buildPhase" }
building
++ command cargo --version
cargo 1.69.0
++ command cargo check --release --all-targets
[0m[0m[1m[32m   Compiling[0m cc v1.0.79
[0m[0m[1m[32m   Compiling[0m quick-start v0.1.0 (/build/source)
[0m[0m[1m[32m   Compiling[0m libffi-sys v2.3.0
[0m[0m[1m[31merror[0m[1m:[0m failed to run custom build command for `libffi-sys v2.3.0`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/libffi-sys-76008ca1f80207aa/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("gcc")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

  --- stderr
  ./configure: line 2251: config.log: Permission denied
  ./configure: line 2261: config.log: Permission denied
  thread 'main' panicked at 'Configuring libffi', /nix/store/jidz82ydi3p4i6rkwn5sbzv7hfnrbw20-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/libffi-sys-2.3.0/build/common.rs:8:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ipetkov** [comment]
Hi @fracek thanks for the report!

Normally permissions errors are a sign that a build script is trying to write files out side of `$OUT_DIR`, but at a cursory glance [it appears the build script is correctly trying to use `$OUT_DIR` for scratch space](https://github.com/tov/libffi-rs/blob/7cab76104d2bc55f2454db893a924313c302f13a/libffi-sys-rs/build/not_msvc.rs#L99)

My hunch is that [this copy of the source files](https://github.com/tov/libffi-rs/blob/7cab76104d2bc55f2454db893a924313c302f13a/libffi-sys-rs/build/not_msvc.rs#L22) is where the issue lies: when building under Nix the sources will be in the nix store which is readonly by default. Running `cp -R` will end up preserving the permissions which would end up creating a read-only directory in `$OUT_DIR`. That likely needs to be changed to `cp -R --no-preserve=mode,ownership`, so I'd recommend opening an issue upstream!

**Comment by fracek** [comment]
Hi @ipetkov, this looks like it! I had a similar issue with the `librusty_v8` which also copies a file preserving mode/ownership. Thank you for the quick reply!
