### ISSUE TITLE
installCargoArtifactsHook defaults to "use-symlink"

### ISSUE THREAD

**Issue by simonzkl** [ipetkov/crane#441]
I'm not sure if this is intentional, but [installCargoArtifactsHook](https://github.com/ipetkov/crane/blob/bc5fa8cd53ef32b9b827f24b993c42a8c4dd913b/lib/setupHooks/installCargoArtifactsHook.sh#L79) still defaults to `"use-symlink"` while everywhere else the default is `"use-zstd"`.

I can open a PR to fix this. If it's intentional, it would be good to document why.

**Comment by ipetkov** [comment]
> I'm not sure if this is intentional, but [installCargoArtifactsHook](https://github.com/ipetkov/crane/blob/bc5fa8cd53ef32b9b827f24b993c42a8c4dd913b/lib/setupHooks/installCargoArtifactsHook.sh#L79) still defaults to "use-symlink" while everywhere else the default is "use-zstd".

The default value is `use-symlink`; only the `build*Package` variants default to `use-zstd` if `cargoArtifacts` have not been set.

This was intentionally chosen since `use-symlink` offers the lowest disk and CPU usage in general when considering having large chains of derivations which add more and more build artifacts as they run.

The `build*Package` variants apply `use-zstd` when `cargoArtifacts` are not set since at that point we know there is exactly one usage of those artifacts and we can get away with compressing the artifacts as much as possible.

---

We do have incremental compression for `use-zstd` which _should_ offer better disk utilization than before, but a derivation still needs to pay the full CPU cost to unpack all previous artifacts so the defaults have remained the same so far.

**Comment by dpc** [comment]
According to my benchmarks `use-zstd` always performs better e2e, especially now that it's incremental. There are many reasons, but to address this one point:

> needs to pay the full CPU cost to unpack all previous artifacts 

the CPU is idle with nothing to do at that point, and decompression saves IO, which is actually the bottleneck. Even against perfect symlinking, the fact that zstd can just linearly read a file instead of traversing source directory minimizes the theoretical overhead it has.

`use-symlinks` is still only partially symlinking, partially copying stuff, AFAIR. And `use-zstd` generally "just works" because it's less tricky.

I encourage anyone to do a wall time comparison between the two. I'd be interested in cases in which use-zstd is not faster.

**Comment by ipetkov** [comment]
Those aren't bad points, it seems pretty low-risk to change the default when switching back is pretty easy. I could see some minor pitfalls (e.g. deleting a file which is present in a previous archive will come back when the next derivation unpacks it again), but there are other workarounds to be had so not the end of the world
