### ISSUE TITLE
.cargo/config.toml setting runner can still break buildDepsOnly builds

### ISSUE THREAD

**Issue by tv42** [ipetkov/crane#468]
Hi it's me again! Dora has yet more traps hidden.

`.cargo/config.toml`:

```toml
[target.x86_64-unknown-linux-gnu]
runner = "sudo -E"
```

https://github.com/bluecatengineering/dora/blob/cd4e17552998b710378839bb7bf7cc9123516468/.cargo/config.toml#L7-L8

This breaks the `command cargo test --release --locked` command run in `cargoArtifacts` `checkPhase`:

```
buildPhase completed in 2 minutes 56 seconds
@nix { "action": "setPhase", "phase": "checkPhase" }
running tests
++ command cargo test --release --locked
   Compiling libc v0.2.150
...
   Compiling topo_sort v0.1.0 (/build/source/libs/topo_sort)
    Finished release [optimized] target(s) in 56.09s
     Running unittests src/lib.rs (target/release/deps/client_classification-055d512c929023e>
error: test failed, to rerun pass `-p client-classification --lib`

Caused by:
  could not execute process `sudo -E /build/source/target/release/deps/client_classification>

Caused by:
  No such file or directory (os error 2)
```

A workaround is `doCheck = false` in `commonArgs`.

I'm a little unclear why `cargoArtifacts` wants to run the tests on the now-mutilated project, does that actually add value? As opposed to running tests for the dependencies.

**Comment by dpc** [comment]
Oh wow, `sudo` in the `.cargo/config.toml`. Interesting.

That `doCheck` defaulting to `true` is something I advocated changing in the past. To me it doesn't make sense to run `cargo test` as a part of these Rust-building craneLib functions when there are dedicated craneLib commands for testing. But it might depend on how you look at it.

**Comment by ipetkov** [comment]
> I'm a little unclear why cargoArtifacts wants to run the tests on the now-mutilated project, does that actually add value?

Yes the point of doing that is it caches any `dev-dependencies` of the project so that they don't have to be rebuild any time the project's sources also change

---

> That doCheck defaulting to true is something I advocated changing in the past. To me it doesn't make sense to run cargo test as a part of these Rust-building craneLib functions when there are dedicated craneLib commands for testing. But it might depend on how you look at it.

IMO building `dev-dependencies` by default is a much better alternative than the footgun of having to rebuild them every time the project's tests run. If this choice causes problems its much easier to spot and fix with setting `doCheck = false` than the inverse...

Though now that we're talking about it, we just want to _build_ the `dev-dependencies`, we don't really care about running any tests (there won't be tests), so perhaps the better alternative is to pass `--no-run` to the cargo invocation
