### ISSUE TITLE
`crateNameFromCargoToml` doesn't work with workspace inherit

### ISSUE THREAD

**Issue by simonzkl** [ipetkov/crane#479]
Crane fails to fetch the package version when you have a workspace package with `version` set to explicitly inherit from the workspace:

```
craneLib.crateNameFromCargoToml { cargoToml = ./crates/main-package/Cargo.toml; }
```

```
[package]
name = "main-package"
version.workspace = true
```

```
trace: warning: crane will use a placeholder value since `version` cannot be found in /nix/store/h7mb5nccz2fffyq1rj7y0m1v3a5d6cda-source/crates/main-package/Cargo.toml
to silence this warning consider one of the following:
- setting `version = "...";` in the derivation arguments explicitly
- setting `package.version = "..."` or `workspace.package.version = "..."` in the root Cargo.toml
- explicitly looking up the values from a different Cargo.toml via 
  `craneLib.crateNameFromCargoToml { cargoToml = ./path/to/Cargo.toml; }`
```

Having a `Cargo.toml` set up like this is often useful when you want to version a set of crates together, but still have a main crate you want to get the `name` from.

I imagine fixing this is awkward since the function only accepts a single file, and anything more than that might be too expensive to copy into the nix store. Maybe an updated warning message that this isn't supported would do?

**Comment by simonzkl** [comment]
Actually, I guess you could have an API like this where it could fallback on `src + /Cargo.toml` if the `cargoToml` had workspace inheritance:
```
crateNameFromCargoToml { src = ./.; cargoToml = ./crates/main-package/Cargo.toml; }
```

**Comment by ipetkov** [comment]
Hi @simonzkl thanks for the report!

It's somewhat intentional that `crane` will not crawl the source directory looking for the workspace root to inherit (which may or may not be possible to do depending on if the input source is scoped to just a sub directory). In the case of using workspace inheritance it is much easier and simpler for a maintainer to explicitly specify which file to pull from

Though I don't mind updating the error message to make things more clear!
