### ISSUE TITLE
Building `crane-utils` creates `$HOME/.cargo`

### ISSUE THREAD

**Issue by fasterthanlime** [ipetkov/crane#512]
:warning: Disclaimer: this is mildly cursed

So I recently did `nix flake update` on one of my repos, bumping crane from 5c234301a1277e4cc759c23a2a7a00a06ddd7111 to c798790eabec3e3da48190ae3698ac227aab770c, and my CI builds stopped working.

The step that fails is just `nix build .#bin` with [this flake](https://gist.github.com/fasterthanlime/b8a59fa7b773bcd610cee99768f385ec) (which you can't run locally I'm afraid, private code).

This all runs in Forgejo Actions (clone of GitHub Actions powered by act), in a Docker image I cooked myself (with [that flake](https://gist.github.com/fasterthanlime/e9582c4842ef00c581a042bb6057b707)) that contains nix, "manually installed" as single-user root.

Apparently this means there's no sandboxing. Apparently nix sets `$HOME` to `/homeless-shelter` ([yes really](https://nixos.org/manual/nix/unstable/language/derivations.html?highlight=homeless#builder-execution), someone should rename that), and _apparently_ between those eleven commits:

  * https://github.com/ipetkov/crane/compare/5c234301a1277e4cc759c23a2a7a00a06ddd7111...c798790eabec3e3da48190ae3698ac227aab770c

...crane started creating a `$HOME/.cargo` directory. I'm not sure what's in there yet, I'll look further today. Also I'll try to enable sandboxed builds in CI, but since this was probably unintended (and might be done by one of my many dependencies, even!), I'm reporting this here so we all have a canonical place to look at.

---

For reference, here's the tail of a CI log where I was investigating this:

```
copying path '/nix/store/0y99g3631mcl08ym46a5803g0hr4rc8j-clang-16.0.6' from 'https://cache.nixos.org'...
copying path '/nix/store/yqvsk9m8aza2ngwnglvadlgj71vcgwzm-clang-wrapper-16.0.6' from 'https://cache.nixos.org'...
copying path '/nix/store/990qpvw72psz4cnz3axc77bz5srx7kcn-rustc-wrapper-1.75.0' from 'https://cache.nixos.org'...
copying path '/nix/store/ss2mfbqkj13b3zyylggb1wvhdray03nz-cargo-1.75.0' from 'https://cache.nixos.org'...
copying path '/nix/store/k3knq69l3w8hxb9ww90kw5mqdz2siliq-auditable-cargo-1.75.0' from 'https://cache.nixos.org'...
copying path '/nix/store/bxrkvqc91bhpl9d57h2kn2m37r9q55kv-cargo-check-hook.sh' from 'https://cache.nixos.org'...
copying path '/nix/store/fjxi77lnr7gb62qj1iykf1lvsf9szqgj-cargo-build-hook.sh' from 'https://cache.nixos.org'...
building '/nix/store/z2zdzm4nx0c40rjgppxyvzfch7h24qha-crane-utils-0.0.1-vendor.tar.gz.drv'...
building '/nix/store/na0mwj49cvpr62z0wwlpqjki8m38zh84-crane-utils-0.0.1.drv'...
error: home directory '/homeless-shelter' exists; please remove it to assure purity of builds without sandboxing
Now does /homeless-shelter exist?
  File: /homeless-shelter
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 0,663	Inode: 42867791    Links: 3
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-01-31 18:21:42.897264596 +0000
Modify: 2024-01-31 18:21:42.897264596 +0000
Change: 2024-01-31 18:21:42.897264596 +0000
 Birth: 2024-01-31 18:21:42.897264596 +0000
What's in it?
total 12
drwxr-xr-x 3 root root 4096 Jan 31 18:21 .
drwxr-xr-x 1 root root 4096 Jan 31 18:21 ..
drwxr-xr-x 2 root root 4096 Jan 31 18:21 .cargo
Let's install tree -ah and see what's in /homeless-shelter
/var/run/act/workflow/4.sh: line 9: apt: command not found
```

(As you can see, I forgot the image isn't debian-based lol, I may add tree to the ci image later)

**Comment by ipetkov** [comment]
Hey @fasterthanlime thanks for the report!

Hmm, nothing immediately jumps to mind what could be causing this. We explicitly [set `CARGO_HOME` to _not_ use `$HOME`](https://github.com/ipetkov/crane/blob/6754d3a297f03590d2fb33fa39d97762ad3d4927/lib/setupHooks/configureCargoCommonVarsHook.sh#L6)

Except crane-utils itself is built with nixpkg's `buildRustPackage` (we don't use ourselves to build our own utils since https://github.com/ipetkov/crane/pull/431).

Could you share the commit range that changed for `nixpkgs`? I wonder if something changed there...

**Comment by fasterthanlime** [comment]
> Could you share the commit range that changed for `nixpkgs`? I wonder if something changed there...

Yup, here it is: https://gist.github.com/fasterthanlime/a929964d328416ffad45ac6e8ff4d4e8

**Comment by ipetkov** [comment]
Thanks for sharing! I tried to do a quick scan of what changed between the revisions to interesting paths but didn't spot much, so we might have to bisect each of `crane`/nixpkgs to find out the culprit

Here's my advice:

* Run `nix build .#bin -L --override-input crane github:ipetkov/crane/5c234301a1277e4cc759c23a2a7a00a06ddd7111`; if it succeeds then we should bisect `crane` further
* Otherwise, run `nix build .#bin -L --override-input nixpkgs github:NixOS/nixpkgs/9b19f5e77dd906cb52dade0b7bd280339d2a1f3d`; if it succeeds then we should bisect nixpkgs further

There's a number of tools/scripts out there for bisecting Nix things, but here's the easiest way to get set up. I'll use `crane` as the example here but you can do the same for nixpkgs:

```sh
git clone https://github.com/ipetkov/crane
cd crane
git bisect start
git bisect good 5c234301a1277e4cc759c23a2a7a00a06ddd7111
git bisect bad c798790eabec3e3da48190ae3698ac227aab770c
nix run /path/to/your/flake/checkout#bin -L --override-input crane "$(pwd)"
# if the above succeeds, run `git bisect good`
# otherwise run `git bisect bad`
# rinse and repeat
```

**Comment by fasterthanlime** [comment]
Just as I was trying to follow these (lovely) instructions to figure out which commit of whose project was to blame, a "nix flake update" now no longer breaks my build, so, I'm closing this for now.
