### ISSUE TITLE
`error: Cannot find Git revision` when using crate with rev but without branch

### ISSUE THREAD

**Issue by ChronosXYZ** [ipetkov/crane#525]
I got that error when trying to build Rust workspace with transitive dependency of some workspace dependency.
```
error: Cannot find Git revision 'c2d1f83eb1612a462962453cb0703bc93258b173' in ref 'refs/heads/master' of repository 'https://github.com/stevefan1999-personal/rust-igd'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
(use '--show-trace' to show detailed location information)
```

I know that there was a fix for #13, but for some reason this fix doesn't work in my situation.

Entry in `Cargo.lock` file:
```toml
[[package]]
# ...
source = "git+https://github.com/stevefan1999-personal/rust-igd?rev=c2d1f83eb1612a462962453cb0703bc93258b173#c2d1f83eb1612a462962453cb0703bc93258b173"
```

So seems like `allRefs = false`. Or maybe mentioned Git repo is corrupted itself?

**Comment by ipetkov** [comment]
Hi @ChronosXYZ thanks for the report!

Looking at https://github.com/stevefan1999-personal/rust-igd/commit/c2d1f83eb1612a462962453cb0703bc93258b173 I see GitHub displaying `
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`. I suspect the commit isn't reachable by the main branch on the repo (or maybe it isn't reachable from any branch?)

Even if we were to add a parameter for easily specifying `allRefs = true` (which I'm open to in the general sense) when fetching the repo, I'm not sure if it would fix the problem given that as it stands, fetching the repo does not reach the commit itself.

My advice is to push a branch which contains that commit. Then update the `Cargo.toml` dependency to specify that branch _and_ the revision, then update your `Cargo.lock` and try building again!

**Comment by ChronosXYZ** [comment]
Thank you for your advice. I have fixed it by using the proper fork of that repo. I don't think it's a good idea to add support for such a corrupted repo, but maybe it's a thing for other people.

**Comment by ipetkov** [comment]
Definitely the first time I've seen something like this!

I think I'll close this issue out for the time being. I think it would be fairly easy to add a parameter that enables `allRefs = true` when vendoring git dependencies, but since it wouldn't have helped in this scenario I think we can wait until someone else actually runs into it!

**Comment by zmitchell** [comment]
Just ran into this myself:
```
Cannot find Git revision '32de7b26f0ce9aef5bea8046bfdcd15400e73b09' in ref 'master' of repository 'https://github.com/oxidecomputer/typify'
```

**Comment by ipetkov** [comment]
@zmitchell it looks like https://github.com/oxidecomputer/typify is configured to use `main` as the default branch, not `master`. That error suggests to me maybe a lockfile is out of date (or Nix's own git fetch isn't respecting the correct default branch?)

I'd recommend doing `cargo update -p typify` and seeing if that updates the lockfile (assuming you are pinned on a particular commit it might correctly add a `ref` in the locked URL). That or try pointing cargo to the `main` branch instead of a specific commit. Then try building again
