### ISSUE TITLE
Extranous crates in vendored git repo can cause a build failure if they fail to parse

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#60]
I had to switch to use git version of `error-stack` like this:

```
-error-stack = "0.1.1"
+error-stack = { version = "0.1.1", git = "https://github.com/hashintel/hash/", rev="5edddb5" }
```

`cargo build` works fine with it, but `nix build .#foobar` fails with:

```
> nix run .#res.starter
path '/home/dpc/lab/rustshop/services' does not contain a 'flake.nix', searching up
warning: Git tree '/home/dpc/lab/rustshop' is dirty
error: builder for '/nix/store/yj8a6ir4szhq4aa73xhnjwi5bwcxd2xf-services-workspace-deps-deps-0.0.1.drv' failed with exit code 101;
       last 10 log lines:
       >   Unable to update https://github.com/hashintel/hash/?rev=5edddb5#5edddb55
       >
       > Caused by:
       >   failed to update replaced source https://github.com/hashintel/hash/?rev=5edddb5#5edddb55
       >
       > Caused by:
       >   failed to parse manifest at `/nix/store/36f54ndv3y8yr2zhbxy1ss7mhs6jjj80-vendor-cargo-deps/8379b92581444212dd05e8733c6ac22ae88bba0f603ebf7660db6adbcf973197/orchestrator-0.0.0/Cargo.toml`
       >
       > Caused by:
       >   `artifact = …` requires `-Z bindeps` (hash_engine)
       For full logs, run 'nix log /nix/store/yj8a6ir4szhq4aa73xhnjwi5bwcxd2xf-services-workspace-deps-deps-0.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/0bz9mki1h7fhk23i1qf1alpr4zc1bg2i-starter-res-gen-0.0.1.drv' failed to build
```

The problem might be that this crate lives in a subdirectory of larger project?

**Comment by ipetkov** [comment]
Thanks for the report @dpc, this looks like a legitimate bug! Here's what I think is happening:

1. The `error-stack` crate is part of a repository which has multiple crates
2. When we vendor the repository we extract _all_ crates we can find in the repository
3. When we vendor the repository, cargo will try to parse all `Cargo.toml` files it finds in there, even if the crate isn't actually consumed by the dependency that is being built
4. In this particular case a crate name `orchestrator` is part of this repository and is vendored. That crate uses an `artifact` value in its `Cargo.toml` which chokes since it appears to be a nightly-only feature

It sounds a like a possible solution is to update step 2) above to only vendor crates in the Cargo.lock file we care about. This is what `cargo vendor` appears to be doing as it will only vendor the crates that are actually used
