### ISSUE TITLE
Parallelize removeReferencesToVendoredSourcesHook

### ISSUE THREAD

**Issue by DoctorDalek1963** [ipetkov/crane#620]
I've got a Trunk project which uses [`stdweb`](https://github.com/koute/stdweb) for some async stuff in Wasm. For whatever reason, `stdweb` generates `inline1.js`, `inline2.js`, ..., all the way up to `inline936.js`. Each of these files needs to be processed by `removeReferencesToVendoredSourcesHook`, but they all get processed one by one. Each of them takes about 5 seconds, so the whole build can take over an hour and a half.

The code in `lib/setupHooks/removeReferencesToVendoredSourcesHook.sh` should be changed to go through all the files in `${installLocation}` in parallel, assuming this is possible with Bash. I believe this could be done with GNU Parallel, but I'm not an expert.

I could probably remove the `stdweb` dependency from my project, but I think parallelizing this hook in crane will speed up a lot of builds for other people as well.

**Comment by dpc** [comment]
Re #167

**Comment by DoctorDalek1963** [comment]
I might be misunderstanding but it seems like that conversation parallelized multiple replacements in a single file. This issue is about removing references across lots of files.

**Comment by dpc** [comment]
Yes. It's just a continuation of previous efforts to speed up this function.

**Comment by ipetkov** [comment]
Hi @DoctorDalek1963 thanks for the report and accompanying PR!

Do you have a representative sample I can look at as a benchmark? I'm not familiar enough with trunk/`stdweb` to whip one up myself :smile:

**Comment by DoctorDalek1963** [comment]
I used my [Tic-tac-toe](https://github.com/DoctorDalek1963/tic-tac-toe) project to test this PR. Just build the `web` package of the flake before and after the commit where I switched to my fork.

**Comment by ipetkov** [comment]
I've opened https://github.com/ipetkov/crane/pull/625 which fixes a pretty embarrassing bug (re-crawling the vendor dir for each installed file) which gives me a pretty good speed up. Trying to run `sed` in parallel (via `xargs -P0`) seemed slower in my synthetic benchmark but it might just be something due to my test files being small/identical

**Comment by ipetkov** [comment]
So it does look like crawling vendorDir was the real bottleneck... Here's what I found:

* without #625 stripping the references takes ~4m8s on my machine
* with #625 stripping the references takes ~6.5s (i.e. invoke `sed` once per file)
* with #625 running  `find "${installLocation}" -type f | xargs -P0 -n1 sed -i'' -f "${sedScript}"` takes ~1.65s
* with #625 running `find "${installLocation}" -type f | xargs sed -i'' -f "${sedScript}"` takes ~0.55s

From these observations it appears that trying to run `sed` in parallel (at least on my machine) doesn't give us much benefit, probably due to the cost of having to fork/exec multiple times and then have `sed` read out the script file and compile the regex. It appears that doing one big invocation is able to amortize that startup cost way more efficiently...

**Comment by ipetkov** [comment]
With the final changes in #625 I was able to bring down the phase runtime to ~0.46s on my machine which I think is pretty good considering where we started!

Thanks again for the report and the reproduction!

**Comment by DoctorDalek1963** [comment]
Yep, #625 fixes this problem and makes the reference stripping happen almost instantly. Thanks!
