### ISSUE TITLE
overrideToolchain does not correctly splice cargo when vendoring git deps

### ISSUE THREAD

**Issue by matthiasbeyer** [ipetkov/crane#628]
**Describe the bug**

I have a repository with a cargo workspace that needs to import one dependency via `rev = "<commit hash>"`. Unfortunately, crane does not handle that as expected.

**Reproduction**

I managed to get this issue reproduced even without a workspace here, with the `bevy` repository as dependency which is also the same dependency I am using in my non-minimal example, with the same commit hash actually. Unfortunately I cannot share that actual repository, as it is closed source for now.

Here's the minimal reproduction: https://github.com/matthiasbeyer/test-crane-gitrev

---

The output of a `nix build` call on that repository:

```
error: builder for '/nix/store/mn1rqjzfjlw9zqrlag17ikjr5na21iqi-test-crane-gitrev-deps-0.1.0.drv' failed with exit code 101;                                                                                        
       last 10 log lines:                                                                                                                                                                                           
       > Running phase: configurePhase                                                                                                                                                                              
       > will append /build/source/.cargo-home/config.toml with contents of /nix/store/b7fxdayj4kjhca5szrl4ghpnzgwk600r-vendor-cargo-deps/config.toml                                                               
       > default configurePhase, nothing to do                                                                                                                                                                      
       > Running phase: buildPhase                                                                                                                                                                                  
       > ++ command cargo --version                                                                                                                                                                                 
       > cargo 1.78.0 (54d8815d0 2024-03-26)                                                                                                                                                                        
       > ++ command cargo check --release --locked --all-targets                                                                                                                                                    
       > error: no matching package named `bevy_reflect` found                                                                                                                                                      
       > location searched: https://github.com/bevyengine/bevy.git?rev=6d25545c516b2fb7698334c428b9cefdee12281e#6d25545c                                                                                            
       > required by package `test-crane-gitrev v0.1.0 (/build/source)`                                                                                                                                             
       For full logs, run 'nix-store -l /nix/store/mn1rqjzfjlw9zqrlag17ikjr5na21iqi-test-crane-gitrev-deps-0.1.0.drv'.                                                                                              
error: 1 dependencies of derivation '/nix/store/7q7f3k60bslx9g3pwq0bpp0qhh3h9jjy-test-crane-gitrev-0.1.0.drv' failed to build   
```

**Comment by ipetkov** [comment]
Hey @matthiasbeyer thanks for the bug report and the reproduction!

Long story short, this is basically a problem with our (lack of) splicing... When we [vendor git deps we use pkgsBuildBuild.cargo](https://github.com/ipetkov/crane/blob/19ca94ec2d288de334ae932107816b4a97736cd8/lib/downloadCargoPackageFromGit.nix#L7) so that when cross compiling we don't end up trying to run a cross compiled version of cargo when vendoring git deps.

Except [when using `.overrideToolchain`](https://github.com/ipetkov/crane/blob/19ca94ec2d288de334ae932107816b4a97736cd8/lib/default.nix#L61-L66) it does not actually splice the new `toolchain.cargo` version into `pkgsBuildBuild` the way our scope sees it, so we're going to have to figure out how to use `makeScopeWithSplicing'` instead of just `makeScope newScope`, but I couldn't quite get things working at a first attempt.

As a workaround I'd recommend trying to use the [dependency source patching](https://crane.dev/patching_dependency_sources.html) technique but replacing the `cargo` in `nativeBuildInputs` with the cargo from `rustToolchain.cargo`

**Comment by matthiasbeyer** [comment]
Awesome, that fixed the issue.

For others that find this issue: I changed my toolchain to be built from nixpkgs unstable (as of 2024-05-27) which fixed my issue.

Thanks @ipetkov for your fast reply and help! :tada:

**Comment by ipetkov** [comment]
Opened https://github.com/ipetkov/crane/pull/634 which looks like it fixes the originally reported issue (for anyone else who might hit the same situation)
