### ISSUE TITLE
Single-derivation vendoring

### ISSUE THREAD

**Issue by johnbchron** [ipetkov/crane#630]
**Is your feature request related to a problem? Please describe.**
I build all my projects that use crane in Github Actions, and I use the [Magic Nix Cache](https://github.com/DeterminateSystems/magic-nix-cache), which uses the Github Actions cache API. When I build a large project, it will very quickly pull in the source for all 600-something crates I'm using as separate derivations, and most of the time it quickly overwhelms the GH actions cache rate limit and ends up downloading the second half of them from the registry.

**Describe the solution you'd like**
It would be awesome if there were an option to vendor all dependencies in a single derivation (with no references to other source derivations), so that my CI can just pull in everything as a single bundle.

**Describe alternatives you've considered**
I can't think of any alternatives to try.

**Additional context**
I understand that the tradeoff here is a complete cache-miss anytime you change a dependency, but I think it's worth it in cases where you're commonly working with ephemeral nix store but persistent caches (like this GH actions setup), and where the dependencies change infrequently. So it would definitely only make sense as an opt-in option.

**Comment by dpc** [comment]
I remember there was an existing request and discussion about grouping these.

IMO an option to e.g. group them by the first letter etc. would be a reasonable middle-ground.

**Comment by ipetkov** [comment]
Unfortunately there isn't much we can do about one-derivation-per-cargo-crate without having to manually updating a fixed output hash (like `pkgs.rustPlatform.buildRustPackage`). Basically we leverage the fact that the `Cargo.lock` already contains checksums we can directly plug into `fetchurl`, but if we wanted to vendor everything in one go, we would need to use a fixed output derivation (which can effectively access the network and run `cargo vendor` directly).

I'm not entirely sure if switching from a symlink to copying all the sources in the "final" vendor derivation would fix the problem. I suppose if Nix's caching is smart enough it would know to only pull the one resulting derivation instead of all the intermediate packages, but if you changed even one dependency you'd need to rebuild that entire derivation again which would hit the rate limiting issue once again.

**Comment by johnbchron** [comment]
My perspective is that right now I hit the rate limit every time. I change dependencies maybe once every 200 runs, so I'm not very worried about the worst case, only the common case.

I think if we copied instead of symlinking and made sure to patch the paths properly, that would probably fix it. I can attempt the change but I might not get very far.

**Comment by dpc** [comment]
BTW. That rate-limit internal thing is a rather severe Magic Nix Cache limitation. Seems like GHA cache expect a few chunkier accesses to store/retrieve bigger compressed artifacts, while Nix projects generally consist of a lot of smaller derivations.

By compressing the `./target` crane might already be in much better situation than some other Rust in Nix building solutions. Not sure how much is it justfied to pile complexity in crane to workaround a limitation of a different project.

Maybe it would make more sense to add some logic to Magic Nix Cache itself to bandaid stuff like this. Eg. a regex to group certain derivations together, and/or some extra tracking on cache side

**Comment by johnbchron** [comment]
Yeah that sounds reasonable. It seems that the rate limit would be an issue for any project where the derivation count is high but the total size is low, so I'll make an issue over there.
