### ISSUE TITLE
Support `buildType` and `checkType`

### ISSUE THREAD

**Issue by yanganto** [ipetkov/crane#727]
**Is your feature request related to a problem? Please describe.**
Support debug build

**Describe the solution you'd like**
There are `buildType` and `checkType` in `rustPlatform.buildRustPackage`, and it can build debug binary.  It is good the let these option also work in `buildDepsOnly`.

If this proposal is good, I am happy to work on this.

**Additional context**
[Building a package in debug mode of Rust in nix](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#building-a-package-in-debug-mode-building-a-package-in-debug-mode)

**Comment by ipetkov** [comment]
Hi @yanganto! `buildDepsOnly` (along with `cargoBuild`, `buildPackage`, and pretty much all others) [support setting `CARGO_PROFILE` to control](https://github.com/ipetkov/crane/blob/f235b656ee5b2bfd6d94c3bfd67896a575d4a6ed/docs/API.md#L105-L107) what value is passed to `cargo build --profile ...`!

If you want to run tests with debug artifacts the better approach is to use a distinct `buildDepsOnly` derivation with `CARGO_PROFILE = "debug";` since trying to mix and match debug and release artifacts in the same derivation is going to cause rebuilds

**Comment by yanganto** [comment]
I got it, I will use this way, thanks.
