### ISSUE TITLE
Target saved into `$out` even when 

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#74]
I have a test that I run with `buildPackage` like: https://github.com/fedimint/fedimint/blob/41ace18a67e1131f146b8aa9ed117f245b9fe275/flake.nix#L170

Documentation for `buildPackage` says that `doInstallCargoArtifacts` is disabled for it by default https://github.com/ipetkov/crane/blob/master/docs/API.md#optional-attributes-1

Yet the output contains heavy `target.tar.zst`. Am I confused or something is not working like it should?

```
[I] dpc@futex:~/l/minimint
> nix build .#cli-test.rust-tests --print-out-paths
/nix/store/9mhviiwwc3a73ifvbszwjxn0mawpy2bq-cargo-package-0.0.1
[I] dpc@futex:~/l/minimint
> ls -alh /nix/store/9mhviiwwc3a73ifvbszwjxn0mawpy2bq-cargo-package-0.0.1
total 443M
dr-xr-xr-x 1 root root     28 Dec 31  1969 .
drwxrwxr-t 1 root nixbld  27M Aug 12 19:57 ..
-r--r--r-- 1 root root   443M Dec 31  1969 target.tar.zst
```

**Comment by dpc** [comment]
Oh. It seems that setting `doInstallCargoArtifacts` explicitly to `false` did the trick, so I guess it's either the documentation or the default being wrong?

**Comment by ipetkov** [comment]
`cargoBuild` will default `doInstallCargArtifacts = true` based on the assumption that other derivations may want to consume them. 

`buildPackage` will default `doInstallCargoArtifacts = false` since it will install binaries to the derivation's output with the assumption that's all the caller wants. 

My recommendation is to either set `doInstallCargoArtifacts = false` (as you have done) or use `buildPackage` if you just want the final binaries

**Comment by dpc** [comment]
I want just to run an integration test from inside them (ref #66). :)


Documentation of `cargoBuild` does not say anything about `doInstallCargArtifacts`, and of`buildPackage` says it's a version of `cargoBuild` and sets `doInstallCargArtifacts = true`, so I guess that's how I've got confused.

**Comment by ipetkov** [comment]
> Documentation of cargoBuild does not say anything about doInstallCargArtifacts

Ah yeah it seems this was omitted (since everything is delegated to `mkCargoDerivation` which sets the default), I'll tweak the docs on this
