### ISSUE TITLE
Something is printing wget output

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#91]
While introducing flake.nix using `crane` to another project (and thus updating flake which updates `crane`) I noticed wget output when doing `nix build -L ...`

![Screenshot from 2022-08-27 23-01-30](https://user-images.githubusercontent.com/9209/187060094-d4e5c0eb-fcf4-4d93-9382-d35c52d78141.png)

**Comment by ipetkov** [comment]
Those are the logs from fetching the tarballs from crates.io, and passing in `-L` to `nix build` shows those logs so seems like it's working as expected!

The output is interleaved since the build jobs are running in parallel on different CPUs. Since the tarballs are cached you won't see those logs when you build again

**Comment by dpc** [comment]
Are these progress bars non-removable? For stuff like crates that downloads usually so fast, they don't seem particularly useful.

**Comment by ipetkov** [comment]
The `fetchurl` implementation comes from nixpkgs. I think it may be possible to suppress the output by messing with the `NIX_CURL_FLAGS` environment variable in the CI, but it might not be worth the effort. These derivations are only built when the `Cargo.lock` changes so hopefully they don't show up in the logs too much
